import { defineConfig } from 'drizzle-kit';

// Canonical DDL is packages/ledger/migrations/0001_baseline.sql (source of truth, ADR-0016).
// That file is GENERATED by scripts/squash-migrations.sh, not written by hand.
// The Drizzle table definitions in packages/ledger/src/schema-pg.ts mirror that DDL and
// are filled in during the ledger implementation slice.
export default defineConfig({
  dialect: 'postgresql',
  schema: './packages/ledger/src/schema-pg.ts',
  out: './packages/ledger/migrations',
  dbCredentials: { url: process.env.DATABASE_URL ?? '' },
});
