import { defineConfig } from 'drizzle-kit';

// Canonical DDL is packages/ledger/migrations/0001_baseline.sql (source of truth, ADR-0016).
// That file is GENERATED by scripts/squash-migrations.sh, not written by hand.
// The Drizzle table definitions in packages/ledger/src/schema-pg.ts mirror that DDL, and
// packages/ledger/src/schema-matches-migrations.unit.test.ts compares the two on every run.
//
// `out` DELIBERATELY DOES NOT POINT AT THE MIGRATION CHAIN, and pointing it back there
// is the defect this line replaced. It used to name packages/ledger/migrations, so
// `drizzle-kit generate` wrote a 0000_*.sql dump into the chain and exited 0 — and
// "0000_" sorts BELOW 0001_baseline.sql, which is the order runMigrations applies files
// in. `drizzle-kit check` wrote a meta/_journal.json there too. Nothing in this
// repository reads either: migrations are hand-written numbered files applied by
// runMigrations against schema_migrations, so drizzle-kit's output is debris at best
// and an unapplicable chain at worst. See scripts/how-migrations-are-authored.mjs,
// which is what `pnpm db:generate` and `pnpm db:migrate` now run.
//
// A throwaway path keeps the config USABLE — schema still resolves, so
// `drizzle-kit generate` remains the way to see the SQL Drizzle would emit — while
// making it unable to reach the chain. .gitignore covers it.
export default defineConfig({
  dialect: 'postgresql',
  schema: './packages/ledger/src/schema-pg.ts',
  out: './.drizzle-out',
  dbCredentials: { url: process.env.DATABASE_URL ?? '' },
});
