// Copyright 2026 The Ownpace authors (Apache-2.0)

/**
 * A COUNTER NO DEFAULT NAMES (workplan 0150, 2026-09-29; scripted 2026-10-03).
 *
 * Nextcloud's converter (`occ db:convert-type`) copies every row with its id,
 * then moves each id counter past them in its last step, which finds a
 * counter's table through the column whose DEFAULT names it. Nextcloud 34 has
 * counters no default names: oc_jobs, oc_previews, oc_preview_locations and
 * oc_preview_versions on a fresh install, whose ids Nextcloud makes itself. The
 * step stops at the first one with `SELECT setval('…', (SELECT MAX() FROM ))`,
 * after the copy and before config.php is switched: on the OTA stack at the
 * preview counter (2026-09-29), on a fresh install at oc_jobs's.
 * `deploy/compose/nextcloud-counters.sql` is that step done right, and what
 * `nextcloud-to-postgres.sh --convert` runs: each counter found through the
 * column pg_depend says owns it, set to the highest id in that column WITHIN
 * THE COUNTER'S OWN RANGE, one counter at a time.
 *
 * It runs here on PGlite, read from the repository as it is, against every
 * kind of counter the OTA stack and a fresh install held:
 *   - an ordinary serial;
 *   - an identity column's;
 *   - a serial whose default Nextcloud dropped, its ids made elsewhere (the
 *     preview case);
 *   - an int4 counter on a bigint column holding Nextcloud's own 64-bit ids
 *     beside the small ones the counter made (oc_jobs on the OTA stack, and
 *     the range the second attempt there added);
 *   - the same with no small id at all;
 *   - an empty table's.
 * Left alone: a counter nothing owns, and a table outside the prefix. A counter
 * that cannot be set is counted and does not stop the rest. Each case asks the
 * database for the id the next row gets, by inserting one.
 */

import { describe, it, expect, afterEach } from 'vitest';
import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SQL = readFileSync(join(REPO_ROOT, 'deploy', 'compose', 'nextcloud-counters.sql'), 'utf8');

// Resolved from the ledger package, where the dependency is declared.
const requireFromLedger = createRequire(join(REPO_ROOT, 'packages', 'ledger', 'package.json'));
interface PgliteLike {
  query<T>(sql: string, params?: unknown[]): Promise<{ rows: T[] }>;
  exec(sql: string): Promise<unknown>;
  close(): Promise<void>;
}
type PgliteCtor = new () => PgliteLike;
const { PGlite } = requireFromLedger('@electric-sql/pglite') as { PGlite: PgliteCtor };

const open: PgliteLike[] = [];
afterEach(async () => {
  for (const db of open.splice(0)) await db.close();
});

/** What the OTA stack and a fresh Nextcloud 34 install held, by kind. */
const NEXTCLOUD_TABLES = `
CREATE TABLE oc_accounts_data (id bigserial PRIMARY KEY, v text);
INSERT INTO oc_accounts_data (id, v) SELECT g, 'copied' FROM generate_series(1, 57) g;

CREATE TABLE oc_ident (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v text);
INSERT INTO oc_ident (id, v) SELECT g, 'copied' FROM generate_series(1, 9) g;

CREATE TABLE oc_preview_locations (id bigserial PRIMARY KEY, v text);
ALTER TABLE oc_preview_locations ALTER COLUMN id DROP DEFAULT;
INSERT INTO oc_preview_locations (id, v) VALUES (7372036854775807, 'made by nextcloud');

CREATE TABLE oc_jobs (id serial PRIMARY KEY, v text);
ALTER TABLE oc_jobs ALTER COLUMN id TYPE bigint;
INSERT INTO oc_jobs (id, v) VALUES (3, 'old'), (41, 'old'), (134826465205002241, 'new'), (134826465205009999, 'new');

CREATE TABLE oc_jobs_new (id serial PRIMARY KEY, v text);
ALTER TABLE oc_jobs_new ALTER COLUMN id TYPE bigint;
INSERT INTO oc_jobs_new (id, v) VALUES (134826465205002241, 'new');

CREATE TABLE oc_empty (id bigserial PRIMARY KEY, v text);

CREATE SEQUENCE oc_stray_seq;
SELECT setval('oc_stray_seq', 500);

CREATE TABLE other_things (id bigserial PRIMARY KEY, v text);
INSERT INTO other_things (id, v) VALUES (5, 'not nextcloud');
`;

async function aDatabase(extra = ''): Promise<PgliteLike> {
  const db = new PGlite();
  open.push(db);
  await db.exec(NEXTCLOUD_TABLES + extra);
  return db;
}

/** Runs the file as nextcloud-to-postgres.sh does, with the prefix it is given, and reads its last line. */
async function setCounters(db: PgliteLike, prefix?: string): Promise<string> {
  if (prefix !== undefined) await db.exec(`SET ownpace.nextcloud_prefix = '${prefix}'`);
  await db.exec(SQL);
  const { rows } = await db.query<{ said: string }>(`SELECT current_setting('ownpace.nextcloud_counters') AS said`);
  return rows[0]!.said;
}

/** The id the next row gets, asked by inserting one. */
async function nextId(db: PgliteLike, table: string): Promise<string> {
  const { rows } = await db.query<{ id: string }>(`INSERT INTO ${table} (v) VALUES ('next') RETURNING id::text AS id`);
  return rows[0]!.id;
}

describe('the counters a copy leaves behind, set from the column that owns each', () => {
  it('holds int4 counters on the bigint columns, as the OTA stack did (the fixture is what it says)', async () => {
    const db = await aDatabase();
    const { rows } = await db.query<{ max: string }>(
      `SELECT seqmax::text AS max FROM pg_sequence WHERE seqrelid = 'oc_jobs_id_seq'::regclass`,
    );
    expect(rows[0]!.max).toBe('2147483647');
  });

  it('sets every counter a column owns, and says so in its last line', async () => {
    const db = await aDatabase();
    expect(await setCounters(db)).toBe('6|0');
  });

  it('moves an ordinary counter past the highest id copied', async () => {
    const db = await aDatabase();
    await setCounters(db);
    expect(await nextId(db, 'oc_accounts_data')).toBe('58');
  });

  it("moves an identity column's counter, which no default names", async () => {
    const db = await aDatabase();
    await setCounters(db);
    expect(await nextId(db, 'oc_ident')).toBe('10');
  });

  it('sets the counter whose default Nextcloud dropped, where the converter stopped on the OTA stack', async () => {
    const db = await aDatabase();
    await setCounters(db);
    const { rows } = await db.query<{ id: string }>(`SELECT nextval('oc_preview_locations_id_seq')::text AS id`);
    expect(rows[0]!.id).toBe('7372036854775808');
  });

  it("counts only the ids within the counter's range: the old small ones, not Nextcloud's own", async () => {
    const db = await aDatabase();
    await setCounters(db);
    expect(await nextId(db, 'oc_jobs')).toBe('42');
  });

  it('starts a counter over when none of its ids is in its range', async () => {
    const db = await aDatabase();
    await setCounters(db);
    expect(await nextId(db, 'oc_jobs_new')).toBe('1');
  });

  it("starts an empty table's counter at its start", async () => {
    const db = await aDatabase();
    await setCounters(db);
    expect(await nextId(db, 'oc_empty')).toBe('1');
  });

  it('leaves a counter nothing owns, and a table outside the prefix, as they were', async () => {
    const db = await aDatabase();
    await setCounters(db);
    const { rows } = await db.query<{ id: string }>(`SELECT nextval('oc_stray_seq')::text AS id`);
    expect(rows[0]!.id).toBe('501');
    expect(await nextId(db, 'other_things')).toBe('1');
  });

  it('gives the same next ids when run twice', async () => {
    const db = await aDatabase();
    expect(await setCounters(db)).toBe('6|0');
    expect(await setCounters(db)).toBe('6|0');
    expect(await nextId(db, 'oc_accounts_data')).toBe('58');
    expect(await nextId(db, 'oc_jobs')).toBe('42');
  });

  it('counts a counter it cannot set, and sets the rest', async () => {
    // A counter owned by a text column: its range cannot be compared with the
    // column, and the statement for it fails.
    const db = await aDatabase(`
      CREATE TABLE oc_odd (code text PRIMARY KEY, v text);
      CREATE SEQUENCE oc_odd_seq OWNED BY oc_odd.code;
    `);
    expect(await setCounters(db)).toBe('6|1');
    expect(await nextId(db, 'oc_accounts_data')).toBe('58');
    expect(await nextId(db, 'oc_jobs')).toBe('42');
  });

  it("follows the table prefix config.php names, and leaves the others' counters alone", async () => {
    const db = await aDatabase(`
      CREATE TABLE nc_things (id bigserial PRIMARY KEY, v text);
      INSERT INTO nc_things (id, v) VALUES (12, 'copied');
    `);
    expect(await setCounters(db, 'nc_')).toBe('1|0');
    expect(await nextId(db, 'nc_things')).toBe('13');
    // Left where the copy left it, which is what collides: asked, not inserted.
    const { rows } = await db.query<{ id: string }>(`SELECT nextval('oc_accounts_data_id_seq')::text AS id`);
    expect(rows[0]!.id).toBe('1');
  });

  it('takes `oc_` when no prefix is given', async () => {
    const db = await aDatabase();
    expect(await setCounters(db, '')).toBe('6|0');
  });
});
