// Copyright 2026 The Ownpace authors (Apache-2.0)

/**
 * A HEALTHCHECK THAT ASKED THE WRONG ADDRESS.
 *
 * `ownpace-www` was marked unhealthy every thirty seconds from 2026-08-20 to
 * 2026-08-25 — five days — and nobody noticed, because `www.yml` is not part of
 * the managed stack and the gate's residue check only speaks for `managed.yml`.
 * Found by reading `docker ps | grep unh` on the Spark while chasing a
 * different unhealthy container.
 *
 *     "FailingStreak": 39
 *     "Output": "wget: can't connect to remote host: Connection refused"
 *
 * REFUSED, NOT 404. That distinction is the whole diagnosis: the request never
 * reached nginx at all, which is also why the container's log carried no access
 * line for it. An empty `dist` would have produced a 404 *and* a log line; this
 * produced neither.
 *
 * The cause is two ordinary decisions meeting:
 *
 *   1. `www-nginx.conf` is bind-mounted onto `/etc/nginx/conf.d/default.conf`
 *      READ-ONLY. The base image's `10-listen-on-ipv6-by-default.sh` exists to
 *      append `listen [::]:80;` to exactly that file, cannot, and says so on
 *      every single start:
 *
 *        can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
 *
 *      So nginx listens on IPv4 only.
 *
 *   2. The healthcheck asked `http://localhost/`, and busybox wget resolves
 *      `localhost` to `::1` first. Nothing was serving there.
 *
 * `apps/web/Dockerfile` got both halves right, by accident rather than by
 * design: it asks `127.0.0.1:80` explicitly, AND its config is generated by
 * envsubst into a writable path so the ipv6 script succeeds. Either alone would
 * have saved it.
 *
 * THIS IS NOT "NEVER USE localhost". `nextcloud` in `managed.yml` asks
 * `http://localhost/status.php` and is genuinely healthy — nothing mounts over
 * its config, so it listens on both stacks. A rule that flagged it would be
 * wrong, and would be the fifth guard in a week to cry wolf on its first run.
 *
 * The rule is the CONJUNCTION: a service whose nginx config is mounted
 * read-only has no IPv6 listener, so its healthcheck must name an address that
 * does not depend on resolution. Both halves are read from the compose file, so
 * a future service that mounts a config read-only and asks `localhost` fails
 * here rather than sitting unhealthy for five days.
 */

import { describe, it, expect } from 'vitest';
import { readdirSync, readFileSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const COMPOSE = join(REPO_ROOT, 'deploy/compose');

type Service = {
  image?: string;
  volumes?: string[];
  healthcheck?: { test?: string[] | string };
};

/** Every compose file in deploy/compose, with its services. */
const composeFiles = readdirSync(COMPOSE)
  .filter((f) => f.endsWith('.yml') || f.endsWith('.yaml'))
  .map((f) => ({ file: relative(REPO_ROOT, join(COMPOSE, f)), text: readFileSync(join(COMPOSE, f), 'utf8') }))
  .map((f) => ({ ...f, doc: parseYaml(f.text) as { services?: Record<string, Service> } }))
  .filter((f) => f.doc?.services);

/**
 * A config mounted over `/etc/nginx/conf.d/` read-only is one the entrypoint
 * cannot add an IPv6 listener to. `:ro` is what makes it unwritable; a
 * read-write mount would be modified in place and is not this rule's business.
 */
function nginxConfIsReadOnly(service: Service): boolean {
  return (service.volumes ?? []).some(
    (v) => typeof v === 'string' && /:\/etc\/nginx\/conf\.d\/[^:]*:ro$/.test(v),
  );
}

/** The healthcheck command as one string, however compose spelled it. */
function healthcheckText(service: Service): string {
  const test = service.healthcheck?.test;
  if (!test) return '';
  return Array.isArray(test) ? test.join(' ') : String(test);
}

const withReadOnlyNginxConf = composeFiles.flatMap(({ file, doc }) =>
  Object.entries(doc.services!)
    .filter(([, s]) => nginxConfIsReadOnly(s))
    .map(([name, s]) => ({ file, name, healthcheck: healthcheckText(s) })),
);

describe('a healthcheck that asked the wrong address', () => {
  it('finds the services this rule is about, so it cannot pass on an empty list', () => {
    // If the walk stops finding www, the rule is asleep and the defect can
    // return unnoticed — which is exactly how it survived five days.
    expect(withReadOnlyNginxConf.map((s) => s.name)).toContain('www');
  });

  it.each(withReadOnlyNginxConf.map((s) => [`${s.file} → ${s.name}`, s.healthcheck] as const))(
    '%s mounts its nginx conf read-only, so it asks an address that needs no resolution',
    (label, healthcheck) => {
      if (!healthcheck) return; // no healthcheck at all is a different question
      expect(
        /\blocalhost\b/.test(healthcheck),
        `${label} mounts /etc/nginx/conf.d/... :ro, so 10-listen-on-ipv6-by-default.sh\n` +
          'cannot add `listen [::]:80;` and nginx serves IPv4 only. Asking `localhost`\n' +
          'resolves to ::1 first and the healthcheck is refused forever — ownpace-www\n' +
          'sat unhealthy for five days that way. Use 127.0.0.1 explicitly.\n' +
          `  got: ${healthcheck}`,
      ).toBe(false);
    },
  );

  it('leaves a healthcheck alone when nothing mounts over its config', () => {
    // nextcloud asks localhost and is genuinely healthy, because its config is
    // writable and it listens on both stacks. A rule that flagged it would be
    // wrong; stating that here keeps the next person from "fixing" it.
    const managed = composeFiles.find((f) => f.file.endsWith('managed.yml'))!;
    const nextcloud = managed.doc.services!.nextcloud;
    expect(nextcloud, 'nextcloud disappeared — re-check this rule s limit').toBeTruthy();
    expect(nginxConfIsReadOnly(nextcloud!)).toBe(false);
    expect(healthcheckText(nextcloud!)).toMatch(/localhost/);
  });

  it('the reason stays next to the address, or it gets "tidied" back', () => {
    const www = readFileSync(join(COMPOSE, 'www.yml'), 'utf8');
    expect(www).toMatch(/127\.0\.0\.1, NOT localhost, AND THAT IS THE WHOLE BUG/);
  });
});
