// Copyright 2026 The Ownpace authors (Apache-2.0)

/**
 * The operative layer cannot drift from its source (ADR-0038).
 *
 * OPERATIVE.md exists so a reader loads a few thousand tokens of live rules
 * instead of a ~50k-token corpus — but a summary that can disagree with its
 * source is the exact disease the register's header warns about (SAD §24's
 * prose list drifted for weeks). So the file is GENERATED from each ADR's own
 * `## Operative rules` section, and this test regenerates and diffs: any state
 * where the two disagree is red, with the fix named.
 */

import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ADR_DIR = join(REPO_ROOT, 'docs', 'adr');
const GENERATOR = join(REPO_ROOT, 'scripts', 'adr-operative.mjs');

const adrFiles = readdirSync(ADR_DIR)
  .filter((f) => /^\d{4}-.+\.md$/.test(f) && !f.startsWith('0000-'))
  .sort();

describe('every ADR states what holds now', () => {
  it.each(adrFiles.map((f) => [f]))('%s has an "## Operative rules" section', (f) => {
    expect(readFileSync(join(ADR_DIR, f), 'utf8')).toContain('\n## Operative rules\n');
  });

  it('the template carries the section, so new ADRs start with it', () => {
    expect(readFileSync(join(ADR_DIR, '0000-template.md'), 'utf8')).toContain(
      '## Operative rules',
    );
  });
});

describe('OPERATIVE.md is build output, not a second source', () => {
  it('matches a fresh regeneration exactly — the drift guard', () => {
    // Run the real generator in check mode rather than reimplementing its
    // assembly here: a reimplementation could drift from the generator, which
    // would guard nothing.
    const r = execFileSync('node', [GENERATOR, '--check'], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
    });
    expect(r).toContain('OPERATIVE.md is current');
  });

  it('covers every ADR — one entry per file, none silently dropped', () => {
    const out = readFileSync(join(ADR_DIR, 'OPERATIVE.md'), 'utf8');
    for (const f of adrFiles) {
      expect(out).toContain(`](./${f})`);
    }
  });

  it('declares itself generated', () => {
    expect(readFileSync(join(ADR_DIR, 'OPERATIVE.md'), 'utf8')).toContain(
      'GENERATED by scripts/adr-operative.mjs',
    );
  });
});

describe('the generator refuses silence', () => {
  // A missing or empty section must be an error, never an omitted entry — an
  // ADR quietly absent from OPERATIVE.md would read as "no constraints", which
  // is the same lie as a skipped test reporting green.
  function runOn(files: Record<string, string>) {
    const dir = mkdtempSync(join(tmpdir(), 'adrop-'));
    try {
      for (const [name, text] of Object.entries(files)) writeFileSync(join(dir, name), text);
      return execFileSync(
        'node',
        [
          '--input-type=module',
          '-e',
          `import { assemble } from '${GENERATOR}'; try { assemble('${dir}'); console.log('OK'); } catch (e) { console.log('ERR: ' + e.message); }`,
        ],
        { encoding: 'utf8' },
      ).trim();
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  }

  it('a missing section is an error naming the file and the convention', () => {
    const out = runOn({ '0099-x.md': '# ADR-0099: X\n\n## Context\nwords\n' });
    expect(out).toContain('ERR:');
    expect(out).toContain('0099-x.md');
    expect(out).toContain('ADR-0038');
  });

  it('an empty section is an error, not an empty entry', () => {
    const out = runOn({
      '0099-x.md': '# ADR-0099: X\n\n## Operative rules\n\n<!-- only a comment -->\n\n## Context\n',
    });
    expect(out).toContain('ERR:');
    expect(out).toContain('is empty');
  });

  it('a well-formed ADR assembles, comments stripped', () => {
    const out = runOn({
      '0099-x.md': '# ADR-0099: X\n\n## Operative rules\n\n<!-- note -->\n\n- the rule\n\n## Context\n',
    });
    expect(out).toBe('OK');
  });

  it('a trailing update blockquote is history, not a rule — excluded', () => {
    // Several ADRs carry `> **Update …**` blocks straight after the metadata;
    // the first assembled OPERATIVE.md republished ADR-0002's update quote as
    // if it were operative. The section ends at a heading OR a blockquote.
    const dir = mkdtempSync(join(tmpdir(), 'adrop-'));
    try {
      writeFileSync(
        join(dir, '0099-x.md'),
        '# ADR-0099: X\n\n## Operative rules\n\n- the rule\n\n> **Update:** narrative history\n\n## Context\n',
      );
      const out = execFileSync(
        'node',
        [
          '--input-type=module',
          '-e',
          `import { extractOperative } from '${GENERATOR}'; import { readFileSync } from 'node:fs'; const r = extractOperative('0099-x.md', readFileSync('${join(dir, '0099-x.md')}', 'utf8')); console.log(JSON.stringify(r.body));`,
        ],
        { encoding: 'utf8' },
      ).trim();
      expect(out).toContain('the rule');
      expect(out).not.toContain('narrative history');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('the register stays an index, not a second corpus', () => {
  const register = readFileSync(join(ADR_DIR, 'README.md'), 'utf8');

  it('no row regrows past one sentence (~400 chars) — the anti-regrowth ratchet', () => {
    // The long rows were the register compensating for unreadable ADRs; the
    // operative sections now carry that weight where the drift guard can see
    // it. A row creeping back toward paragraph length fails here first.
    const rows = register.split('\n').filter((l) => /^\| \[\d{4}\]/.test(l));
    expect(rows.length).toBeGreaterThan(30);
    for (const row of rows) {
      expect(row.length, row.slice(0, 80)).toBeLessThanOrEqual(400);
    }
  });

  it('points readers at OPERATIVE.md for the rules', () => {
    expect(register).toContain('OPERATIVE.md');
  });
});

describe('the protocol is wired where agents read', () => {
  it('AGENTS.md carries the reading protocol and the regen command', () => {
    const agents = readFileSync(join(REPO_ROOT, 'AGENTS.md'), 'utf8');
    expect(agents).toContain('docs/adr/OPERATIVE.md');
    expect(agents).toContain('adr-operative.mjs --write');
  });

  it('CONTRIBUTING.md tells authors about the section and the regeneration', () => {
    const contributing = readFileSync(join(REPO_ROOT, 'CONTRIBUTING.md'), 'utf8');
    expect(contributing).toContain('## Operative rules');
    expect(contributing).toContain('adr-operative.mjs --write');
  });
});
