#!/usr/bin/env node
// Copyright 2026 The Ownpace authors (Apache-2.0)
//
// workplan-index.mjs — assemble the index table in docs/workplans/README.md
// from each plan's own first line, one-line summary, Status heading and task
// table (workplan 0147 T1).
//
// WHY GENERATED. The index was written by hand. It was last verified on
// 2026-08-03, and by 2026-09-24 it had no row for 110 of the plans after it,
// so an agent looking for "which plan covers X" had to open plans one by one,
// which is what the index was there to save. The table is therefore BUILD
// OUTPUT of the plans themselves, never a second source, and `--check` (run in
// CI's docs-hygiene job) fails any state where the two disagree.
//
// Usage:
//   node scripts/workplan-index.mjs --check   # exit 1 on drift or a plan without a summary
//   node scripts/workplan-index.mjs --write   # regenerate the region in docs/workplans/README.md
//
// Deliberately dumb, like adr-operative.mjs: it counts the markers a plan's own
// task table carries and never decides what they mean, whether a plan is done,
// or what comes next. The one sentence per plan is the plan's own
// `> **In one line:**` line, written in the plan, so it cannot drift from it.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'docs', 'workplans');

export const BEGIN = '<!-- BEGIN GENERATED by scripts/workplan-index.mjs — DO NOT EDIT BY HAND. -->';
export const END = '<!-- END GENERATED by scripts/workplan-index.mjs -->';
const HEADER = [
  BEGIN,
  '<!-- Edit the plan\'s own first line, "In one line" or Status block, then run: -->',
  '<!--   node scripts/workplan-index.mjs --write -->',
];

/** The line a plan carries under its title, read into the index's summary column. */
export const SUMMARY_PREFIX = '> **In one line:** ';
/** Longer than this is not one line any more. */
export const SUMMARY_MAX = 300;

/**
 * The status symbols the plans use, in no order of meaning. The first one in a
 * task row's status cell is that row's marker. A new symbol is one entry here,
 * added in the pull request that first uses it.
 */
export const MARKERS = ['✅', '🟢', '🟡', '📋', '⏳', '⬜', '🔨', '🚧', '⛔', '⚠️', '⏸️', '🅿️', '🕓', '📝', '🔎'];

/** A number more than one file may carry, and why. */
export const SHARED_NUMBERS = {
  '0001': '`0001-start-prompt.md` is the historical start prompt, not a plan',
};

/** A number no file carries, and why. Any other gap is listed, never a failure. */
export const KNOWN_GAPS = {
  '0048': 'named in PR #416\'s description and in code comments; no file was ever written (0147 T4)',
  '0049': 'named in PR #416\'s description and in code comments; no file was ever written (0147 T4)',
  '0050': 'named in PR #416\'s description and in code comments; no file was ever written (0147 T4)',
};

/** The files that are not plans although they carry a plan's number. */
const NOT_A_PLAN = new Set(['0001-start-prompt.md']);

/** Plan files: NNNN-*.md, in number order, then file-name order. */
export function planFiles(dir = DIR) {
  return readdirSync(dir)
    .filter((f) => /^\d{4}-.+\.md$/.test(f))
    .sort();
}

const strip = (s) => s.replace(/️/g, '');
const escapeCell = (s) => s.replace(/\|/g, '\\|');

/** The first marker in a status cell, or undefined. Emoji variation selectors are ignored. */
export function markerOf(cell) {
  const text = strip(cell);
  let best;
  let at = Infinity;
  for (const m of MARKERS) {
    const i = text.indexOf(strip(m));
    if (i !== -1 && i < at) {
      at = i;
      best = m;
    }
  }
  return best;
}

function cells(line) {
  const t = line.trim();
  if (!t.startsWith('|')) return undefined;
  // Split on pipes that are not escaped; drop the empty ends.
  const parts = t.replace(/\\\|/g, '\uE000').split('|').map((c) => c.replace(/\uE000/g, '|').trim());
  return parts.slice(1, parts[parts.length - 1] === '' ? -1 : undefined);
}

const isSeparator = (line) => /^\s*\|(\s*:?-{2,}:?\s*\|)+\s*$/.test(line);

/**
 * Read one plan. Throws only for a first line that names another plan's number,
 * which is a sibling's heading copied and not changed; everything else it cannot
 * read is reported in the row's note, never guessed.
 */
export function readPlan(file, text) {
  const number = file.slice(0, 4);
  const lines = text.split('\n');
  const first = (lines[0] ?? '').replace(/^#\s+/, '').trim();

  const lead = /^(?:Workplan\s+)?(\d{4})\b/.exec(first);
  if (lead && lead[1] !== number && !NOT_A_PLAN.has(file)) {
    throw new Error(`${file}: its first line names plan ${lead[1]} — a sibling's heading copied and not changed`);
  }
  const title = first.replace(/^(?:Workplan\s+)?\d{4}\s*(?:[—:–-]\s*)?/, '').trim() || first;

  const firstSection = lines.findIndex((l) => /^## /.test(l));
  const head = firstSection === -1 ? lines : lines.slice(0, firstSection);
  const summaryLine = head.find((l) => l.startsWith(SUMMARY_PREFIX));
  const summary = summaryLine?.slice(SUMMARY_PREFIX.length).trim();
  const supersededBy = /^> ⚠️? ?\*\*SUPERSEDED by \[workplan (\d{4})\]/.exec(
    head.find((l) => /^> ⚠️? ?\*\*SUPERSEDED by \[workplan \d{4}\]/.test(l)) ?? '',
  )?.[1];

  const notes = [];
  let date;
  let rows;
  const markers = new Map();
  let unmarked = 0;

  const statusAt = lines.findIndex((l) => l.startsWith('## Status'));
  if (statusAt === -1) {
    notes.push('no Status block');
  } else {
    const dated = /^## Status — (\d{4}-\d{2}-\d{2})\b/.exec(lines[statusAt]);
    if (dated) date = dated[1];
    else notes.push('undated Status heading');

    let stop = lines.findIndex((l, i) => i > statusAt && /^## /.test(l));
    if (stop === -1) stop = lines.length;
    for (let i = statusAt + 1; i < stop - 1 && rows === undefined; i++) {
      const header = cells(lines[i]);
      if (!header || !isSeparator(lines[i + 1])) continue;
      const hasTask = header.some((c) => /^(Task|Item)$/i.test(c));
      const statusCol = header.findIndex((c) => /^(Status|State)$/i.test(c));
      if (!hasTask || statusCol === -1) continue;
      rows = 0;
      for (let j = i + 2; j < stop; j++) {
        const row = cells(lines[j]);
        if (!row) break;
        rows++;
        const m = markerOf(row[statusCol] ?? '');
        if (m) markers.set(m, (markers.get(m) ?? 0) + 1);
        else unmarked++;
      }
    }
    if (rows === undefined) notes.push('no task table in the Status block');
  }
  if (supersededBy) notes.push(`superseded by ${supersededBy}`);
  if (unmarked) notes.push(`${unmarked} unmarked`);
  if (NOT_A_PLAN.has(file)) notes.push(SHARED_NUMBERS[number] ?? 'not a plan');

  return { file, number, title, summary, date, rows, markers, notes };
}

/** Everything the table needs, plus the problems `--check` refuses. */
export function collect(dir = DIR) {
  const files = planFiles(dir);
  const plans = files.map((f) => readPlan(f, readFileSync(join(dir, f), 'utf8')));

  const byNumber = new Map();
  for (const p of plans) byNumber.set(p.number, [...(byNumber.get(p.number) ?? []), p.file]);
  for (const [n, fs] of byNumber) {
    if (fs.length > 1 && !SHARED_NUMBERS[n]) {
      throw new Error(`plan number ${n} is used by ${fs.join(' and ')} — renumber the newer one (see "Numbering" in docs/workplans/README.md)`);
    }
  }

  const problems = [];
  for (const p of plans) {
    if (NOT_A_PLAN.has(p.file)) continue;
    if (p.summary === undefined) {
      problems.push(`${p.file}: no "${SUMMARY_PREFIX.trim()}" line under the title`);
    } else if (!p.summary || p.summary.length > SUMMARY_MAX) {
      problems.push(`${p.file}: its one-line summary is empty or longer than ${SUMMARY_MAX} characters`);
    }
  }

  const gaps = [];
  const numbers = [...byNumber.keys()].map(Number).sort((a, b) => a - b);
  const highest = numbers[numbers.length - 1] ?? 0;
  for (let n = 1; n < highest; n++) {
    const key = String(n).padStart(4, '0');
    if (!byNumber.has(key)) gaps.push({ number: key, reason: KNOWN_GAPS[key] ?? 'no file on this branch' });
  }
  return { plans, gaps, problems };
}

/** The generated region, BEGIN to END lines included. */
export function assemble(dir = DIR) {
  const { plans, gaps } = collect(dir);
  const totals = new Map(MARKERS.map((m) => [m, 0]));
  let unmarked = 0;
  for (const p of plans) {
    for (const [m, c] of p.markers) totals.set(m, totals.get(m) + c);
    if (p.rows !== undefined) unmarked += p.rows - [...p.markers.values()].reduce((a, b) => a + b, 0);
  }
  const planCount = plans.filter((p) => !NOT_A_PLAN.has(p.file)).length;
  const counted = MARKERS.filter((m) => totals.get(m) > 0).map((m) => `${m} ${totals.get(m)}`);
  if (unmarked) counted.push(`unmarked ${unmarked}`);

  const rows = [
    ...plans.map((p) => ({ number: p.number, file: p.file, p })),
    ...gaps.map((g) => ({ number: g.number, gap: g })),
  ].sort((a, b) => a.number.localeCompare(b.number) || (a.file ?? '').localeCompare(b.file ?? ''));

  const out = [
    ...HEADER,
    '',
    `${planCount} plans. Task rows by the marker their Status cell starts with: ${counted.join(' · ')}.`,
    '',
    '| Plan | Title | In one line | Status as of | Rows | Markers | Note |',
    '|---|---|---|---|---|---|---|',
  ];
  for (const r of rows) {
    if (r.gap) {
      out.push(`| ${r.number} | — | — | — | — | — | no file: ${escapeCell(r.gap.reason)} |`);
      continue;
    }
    const p = r.p;
    const markers = MARKERS.filter((m) => p.markers.has(m)).map((m) => `${m} ${p.markers.get(m)}`).join(' · ');
    out.push(
      `| [${p.number}](./${p.file}) | ${escapeCell(p.title)} | ${escapeCell(p.summary ?? (NOT_A_PLAN.has(p.file) ? '—' : 'no one-line summary'))} | ${p.date ?? '—'} | ${p.rows ?? '—'} | ${markers || '—'} | ${escapeCell(p.notes.join(' · '))} |`,
    );
  }
  out.push('', END);
  return out.join('\n');
}

/** The README with its region replaced. Throws when either marker line is missing. */
export function render(readme, region) {
  const start = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error('docs/workplans/README.md has no generated region — restore its BEGIN and END lines');
  }
  return readme.slice(0, start) + region + readme.slice(end + END.length);
}

/**
 * What `--check` answers for a directory of plans: the README's region against a
 * fresh assembly, and every plan's summary line. `ok` is false with the reasons.
 */
export function check(dir = DIR) {
  const readme = readFileSync(join(dir, 'README.md'), 'utf8');
  const messages = [];
  let want;
  try {
    want = render(readme, assemble(dir));
  } catch (err) {
    return { ok: false, messages: [String(err.message ?? err)] };
  }
  if (want !== readme) {
    messages.push('docs/workplans/README.md is out of date with the plans\' own first lines, summaries and Status blocks.');
    messages.push('Regenerate it:  node scripts/workplan-index.mjs --write');
  }
  const { problems } = collect(dir);
  if (problems.length) {
    messages.push('Every plan carries one line under its title that says what it is about, for the index:');
    messages.push(`  ${SUMMARY_PREFIX}<one sentence, at most ${SUMMARY_MAX} characters, no progress or dates>`);
    for (const p of problems) messages.push(`  - ${p}`);
  }
  return { ok: messages.length === 0, messages };
}

/** Rewrite the README's region for a directory of plans. */
export function write(dir = DIR) {
  const file = join(dir, 'README.md');
  writeFileSync(file, render(readFileSync(file, 'utf8'), assemble(dir)));
  return file;
}

const mode = process.argv[2];
if (mode === '--write') {
  try {
    console.log(`wrote ${write()}`);
  } catch (err) {
    console.error(String(err.message ?? err));
    process.exit(1);
  }
  const { problems } = collect();
  if (problems.length) {
    console.error(`${problems.length} plan(s) have no usable one-line summary; --check will fail:`);
    for (const p of problems) console.error(`  - ${p}`);
    process.exit(1);
  }
} else if (mode === '--check') {
  const { ok, messages } = check();
  if (!ok) {
    for (const m of messages) console.error(m);
    process.exit(1);
  }
  console.log('the workplan index is current');
} else if (mode !== undefined) {
  console.error('usage: workplan-index.mjs [--check | --write]');
  process.exit(2);
}
