// Copyright 2026 The Ownpace authors (Apache-2.0)

/**
 * The workplan index cannot fall behind the plans again (workplan 0147 T1).
 *
 * By 2026-09-24, seven weeks after the index was last verified by hand, 110
 * plans had no row in it, although it had warned three times that this would
 * happen, and an agent looking for the plan that covers a file had to open
 * plans one by one. The table is now build output of each plan's own first
 * line, `> **In one line:**` summary, Status heading and task table, and CI's
 * docs-hygiene job runs `node scripts/workplan-index.mjs --check`.
 *
 * FIXTURES ONLY. A unit test that read the real plans would make every prose
 * commit to a workplan run the whole suite, which
 * `a-doc-a-test-reads-that-ci-skipped` exists to prevent (0147 §1). The real
 * tree is checked by the docs-hygiene job; this file checks that the rules the
 * generator reads by are the ones 0147 T1 lists, and that the job runs it.
 */

import { describe, it, expect, afterEach } from 'vitest';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const GENERATOR = join(REPO_ROOT, 'scripts', 'workplan-index.mjs');

const REGION =
  '<!-- BEGIN GENERATED by scripts/workplan-index.mjs — DO NOT EDIT BY HAND. -->\n' +
  '<!-- END GENERATED by scripts/workplan-index.mjs -->';

const dirs: string[] = [];
afterEach(() => {
  for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
});

function fixture(files: Record<string, string>, readme = `# Index\n\n${REGION}\n`): string {
  const dir = mkdtempSync(join(tmpdir(), 'wpindex-'));
  dirs.push(dir);
  for (const [name, text] of Object.entries(files)) writeFileSync(join(dir, name), text);
  writeFileSync(join(dir, 'README.md'), readme);
  return dir;
}

/** Run one exported function of the real generator on a fixture directory, as JSON. */
function call(fn: 'readPlan' | 'collect' | 'assemble' | 'check' | 'write', dir: string, file?: string): any {
  const argsExpr =
    fn === 'readPlan'
      ? `${JSON.stringify(file)}, readFileSync(${JSON.stringify(join(dir, file ?? ''))}, 'utf8')`
      : JSON.stringify(dir);
  const out = execFileSync(
    'node',
    [
      '--input-type=module',
      '-e',
      `import { readFileSync } from 'node:fs';
       import * as g from ${JSON.stringify(GENERATOR)};
       try {
         const r = g.${fn}(${argsExpr});
         console.log(JSON.stringify({ ok: r, }, (k, v) => (v instanceof Map ? Object.fromEntries(v) : v)));
       } catch (e) { console.log(JSON.stringify({ error: e.message })); }`,
    ],
    { encoding: 'utf8' },
  );
  return JSON.parse(out.trim());
}

const SUMMARY = '> **In one line:** The thing this plan changes, in one sentence.';
const plan = (n: string, opts: { first?: string; summary?: string | null; status?: string; table?: string; banner?: string } = {}) =>
  [
    opts.first ?? `# Workplan ${n} — A plan about something`,
    '',
    ...(opts.summary === null ? [] : [opts.summary ?? SUMMARY, '']),
    ...(opts.banner ? [opts.banner, ''] : []),
    opts.status ?? '## Status — 2026-09-24 (update this block at the end of every session)',
    '',
    opts.table ??
      ['| Task | Status | Notes |', '|---|---|---|', '| T1 One | ✅ Done | x |', '| T2 Two | 📋 **Proposed** | y |'].join('\n'),
    '',
    '## 1. What there is today',
    '',
    'Words.',
    '',
  ].join('\n');

describe('what the generator reads from a plan (0147 T1, rules 2 to 7)', () => {
  it('reads number, title, summary, date, rows and markers from the standard shape', () => {
    const dir = fixture({ '0101-a.md': plan('0101') });
    const { ok } = call('readPlan', dir, '0101-a.md');
    expect(ok).toMatchObject({
      number: '0101',
      title: 'A plan about something',
      summary: 'The thing this plan changes, in one sentence.',
      date: '2026-09-24',
      rows: 2,
      markers: { '✅': 1, '📋': 1 },
      notes: [],
    });
  });

  it.each([
    ['# 0101 — A plan about something'],
    ['# Workplan 0101: A plan about something'],
    ['# Workplan 0101 A plan about something'],
  ])('%s gives the same title as the standard form', (first) => {
    const dir = fixture({ '0101-a.md': plan('0101', { first }) });
    expect(call('readPlan', dir, '0101-a.md').ok.title).toBe('A plan about something');
  });

  it('a first line that names another plan throws, and names the file', () => {
    const dir = fixture({ '0101-a.md': plan('0101', { first: '# Workplan 0100 — Copied from a sibling' }) });
    const r = call('readPlan', dir, '0101-a.md');
    expect(r.error).toContain('0101-a.md');
    expect(r.error).toContain('0100');
  });

  it('a first line that names an ADR later in the line does not throw', () => {
    const dir = fixture({ '0023-a.md': plan('0023', { first: '# Workplan 0023 — The fallback ADR-0006 promised' }) });
    expect(call('readPlan', dir, '0023-a.md').ok.title).toBe('The fallback ADR-0006 promised');
  });

  it('an undated Status heading and a missing one are said, with no counts', () => {
    const undated = fixture({ '0101-a.md': plan('0101', { status: '## Status: COMPLETED', table: 'No table.' }) });
    expect(call('readPlan', undated, '0101-a.md').ok).toMatchObject({
      notes: ['undated Status heading', 'no task table in the Status block'],
    });
    const none = fixture({ '0101-a.md': '# Workplan 0101 — X\n\n' + SUMMARY + '\n\nNo status.\n' });
    const r = call('readPlan', none, '0101-a.md').ok;
    expect(r.notes).toEqual(['no Status block']);
    expect(r.rows).toBeUndefined();
  });

  it('a task table under a later heading is not read', () => {
    const text = plan('0101', { table: 'Prose only.' }) + '## Tasks\n\n| Task | Status |\n|---|---|\n| T1 | ✅ |\n';
    const dir = fixture({ '0101-a.md': text });
    expect(call('readPlan', dir, '0101-a.md').ok.notes).toContain('no task table in the Status block');
  });

  it('counts the first marker of a cell, calls a cell without one unmarked, and never reads ⚠️ as superseded', () => {
    const table = [
      '| Task | Status | Notes |',
      '|---|---|---|',
      '| T1 | (a) ✅ done (b) 📋 proposed | |',
      '| T2 | **Done** | |',
      '| T3 | ⚠️ **Half right** | |',
    ].join('\n');
    const dir = fixture({ '0101-a.md': plan('0101', { table }) });
    const r = call('readPlan', dir, '0101-a.md').ok;
    expect(r.markers).toEqual({ '✅': 1, '⚠️': 1 });
    expect(r.notes).toEqual(['1 unmarked']);
  });

  it('the SUPERSEDED banner under the title is said, also in a file with no Status heading', () => {
    const banner = '> ⚠️ **SUPERSEDED by [workplan 0009](./0009-x.md)** (2026-07-09) — kept as history.';
    const text = `# Workplan 0004 — Old\n\n${SUMMARY}\n\n${banner}\n\nWords.\n`;
    const dir = fixture({ '0004-a.md': text });
    expect(call('readPlan', dir, '0004-a.md').ok.notes).toEqual(['no Status block', 'superseded by 0009']);
  });
});

describe('numbers and summaries across the directory (rules 8 and 9)', () => {
  it('two files with the same number throw, naming both', () => {
    const dir = fixture({ '0101-a.md': plan('0101'), '0101-b.md': plan('0101') });
    const r = call('collect', dir);
    expect(r.error).toContain('0101-a.md');
    expect(r.error).toContain('0101-b.md');
  });

  it('0001 may be shared with the historical start prompt', () => {
    const dir = fixture({ '0001-a.md': plan('0001'), '0001-start-prompt.md': '# OpenHands start prompt — slice 0001\n\nWords.\n' });
    expect(call('collect', dir).ok.problems).toEqual([]);
  });

  it('a missing number is a row, with its known reason, and never a failure', () => {
    const dir = fixture({ '0047-a.md': plan('0047'), '0051-a.md': plan('0051') });
    const r = call('collect', dir).ok;
    expect(r.gaps.map((g: { number: string }) => g.number)).toEqual(expect.arrayContaining(['0048', '0049', '0050']));
    expect(r.gaps.find((g: { number: string }) => g.number === '0048').reason).toContain('0147 T4');
    const table = call('assemble', dir).ok as string;
    expect(table).toContain('| 0048 | — |');
  });

  it('a plan without its one-line summary is a problem, and so is one that is too long', () => {
    const dir = fixture({
      '0101-a.md': plan('0101', { summary: null }),
      '0102-a.md': plan('0102', { summary: `> **In one line:** ${'word '.repeat(80)}` }),
    });
    const problems = call('collect', dir).ok.problems as string[];
    expect(problems.some((p) => p.startsWith('0101-a.md') && p.includes('In one line'))).toBe(true);
    expect(problems.some((p) => p.startsWith('0102-a.md') && p.includes('300'))).toBe(true);
  });

  it('the summary is the table\'s column, and a pipe in it is escaped', () => {
    const dir = fixture({ '0101-a.md': plan('0101', { summary: '> **In one line:** Reads A | B.' }) });
    expect(call('assemble', dir).ok).toContain('| Reads A \\| B. |');
  });
});

describe('--check (the drift guard CI runs)', () => {
  it('passes after --write, and fails when the region was edited by hand', () => {
    const dir = fixture({ '0101-a.md': plan('0101') });
    call('write', dir);
    expect(call('check', dir).ok).toEqual({ ok: true, messages: [] });

    const readme = readFileSync(join(dir, 'README.md'), 'utf8');
    writeFileSync(join(dir, 'README.md'), readme.replace('A plan about something', 'Edited by hand'));
    const r = call('check', dir).ok;
    expect(r.ok).toBe(false);
    expect(r.messages.join('\n')).toContain('node scripts/workplan-index.mjs --write');
  });

  it('fails when a plan changed its Status block and nobody regenerated', () => {
    const dir = fixture({ '0101-a.md': plan('0101') });
    call('write', dir);
    writeFileSync(join(dir, '0101-a.md'), plan('0101', { status: '## Status — 2026-10-01 (update this block)' }));
    expect(call('check', dir).ok.ok).toBe(false);
  });

  it('fails on a README with no region', () => {
    const dir = fixture({ '0101-a.md': plan('0101') }, '# Index\n\nNo region.\n');
    const r = call('check', dir).ok;
    expect(r.ok).toBe(false);
    expect(r.messages.join('\n')).toContain('no generated region');
  });

  it('fails on a plan without a summary even when the region is current', () => {
    const dir = fixture({ '0101-a.md': plan('0101', { summary: null }) });
    call('write', dir);
    const r = call('check', dir).ok;
    expect(r.ok).toBe(false);
    expect(r.messages.join('\n')).toContain('0101-a.md');
  });

  it('CI\'s docs-hygiene job runs it', () => {
    const ci = readFileSync(join(REPO_ROOT, '.github', 'workflows', 'ci.yml'), 'utf8');
    const job = ci.slice(ci.indexOf('\n  docs-hygiene:'), ci.indexOf('\n  fixture-uuid-check:'));
    expect(job).toContain('node scripts/workplan-index.mjs --check');
  });
});
