-- Baseline schema for the ledger (squashed).
--
-- GENERATED — do not hand-edit. Produced by scripts/squash-migrations.sh, which
-- applies the previous migration chain to a throwaway database and dumps the
-- result, then proves the baseline reproduces that schema byte-for-byte.
--
-- This replaces the original 0001..0028 chain, squashed while the product was
-- still pre-release and no database anywhere held real data. The chain is kept in
-- git history; nothing is lost. To add a schema change, write a NEW numbered file
-- alongside this one exactly as before — this file is only ever regenerated by
-- squashing again, which is a deliberate pre-release-only operation.
--
-- Roles are cluster-global, so pg_dump omits them; `app_user` (from the old 0009)
-- is created here first. Everything below is pg_dump output.

-- Application role for RLS enforcement. A non-superuser, because superusers
-- bypass row-level security even when it is FORCEd — so the application must not
-- connect as one. Idempotent: re-running finds the role and does nothing.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user LOGIN PASSWORD 'app_password';
  END IF;
END
$$;

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    actor text,
    action text NOT NULL,
    entity text,
    entity_id uuid,
    detail jsonb,
    at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.audit_log FORCE ROW LEVEL SECURITY;


--
-- Name: backup_target; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.backup_target (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid,
    kind text NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    secret_ref text,
    enabled boolean DEFAULT false NOT NULL,
    last_run_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT backup_target_kind_check CHECK ((kind = ANY (ARRAY['s3'::text, 'webdav'::text, 'local'::text])))
);

ALTER TABLE ONLY public.backup_target FORCE ROW LEVEL SECURITY;


--
-- Name: collection_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.collection_mapping (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid NOT NULL,
    domain text NOT NULL,
    source_collection text NOT NULL,
    target_collection text NOT NULL,
    special_use text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT collection_mapping_domain_check CHECK ((domain = ANY (ARRAY['email'::text, 'calendar'::text, 'contact'::text, 'file'::text]))),
    CONSTRAINT collection_mapping_special_use_check CHECK ((special_use = ANY (ARRAY['\Inbox'::text, '\Sent'::text, '\Drafts'::text, '\Junk'::text, '\Trash'::text, '\Archive'::text])))
);

ALTER TABLE ONLY public.collection_mapping FORCE ROW LEVEL SECURITY;


--
-- Name: connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.connection (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    role text NOT NULL,
    kind text NOT NULL,
    display_name text NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    secret_ref text,
    status text DEFAULT 'connected'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    encrypted_credentials jsonb,
    CONSTRAINT connection_kind_check CHECK ((kind = ANY (ARRAY['o365'::text, 'soverin'::text, 'nextcloud'::text, 'proton'::text, 'imap'::text, 'caldav'::text, 'carddav'::text, 'webdav'::text, 'selfhosted_mail'::text, 'jmap'::text]))),
    CONSTRAINT connection_role_check CHECK ((role = ANY (ARRAY['source'::text, 'target'::text]))),
    CONSTRAINT connection_status_check CHECK ((status = ANY (ARRAY['connected'::text, 'error'::text, 'revoked'::text])))
);

ALTER TABLE ONLY public.connection FORCE ROW LEVEL SECURITY;


--
-- Name: cursor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cursor (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid NOT NULL,
    folder_path text NOT NULL,
    cursor_value text DEFAULT ''::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.cursor FORCE ROW LEVEL SECURITY;


--
-- Name: cutover; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cutover (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid,
    state text DEFAULT 'not_started'::text NOT NULL,
    gate_passed boolean DEFAULT false NOT NULL,
    mx_switched_at timestamp with time zone,
    completed_at timestamp with time zone,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT cutover_state_check CHECK ((state = ANY (ARRAY['not_started'::text, 'verifying'::text, 'gated'::text, 'switched'::text, 'grace'::text, 'done'::text, 'rolled_back'::text])))
);

ALTER TABLE ONLY public.cutover FORCE ROW LEVEL SECURITY;


--
-- Name: cutover_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cutover_event (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid NOT NULL,
    "timestamp" timestamp with time zone DEFAULT now() NOT NULL,
    from_state text,
    to_state text NOT NULL,
    triggered_by text NOT NULL,
    reason text,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    event_type text DEFAULT 'STATE_TRANSITION'::text NOT NULL,
    CONSTRAINT cutover_event_event_type_check CHECK ((event_type = ANY (ARRAY['CUTOVER_INITIALIZED'::text, 'STATE_TRANSITION'::text]))),
    CONSTRAINT cutover_event_from_state_check CHECK ((from_state = ANY (ARRAY['PREPARING'::text, 'READY_FOR_CUTOVER'::text, 'APPROVED'::text, 'CUTOVER_IN_PROGRESS'::text, 'GRACE_PERIOD'::text, 'COMPLETED'::text, 'FAILED'::text, 'ROLLED_BACK'::text]))),
    CONSTRAINT cutover_event_to_state_check CHECK ((to_state = ANY (ARRAY['PREPARING'::text, 'READY_FOR_CUTOVER'::text, 'APPROVED'::text, 'CUTOVER_IN_PROGRESS'::text, 'GRACE_PERIOD'::text, 'COMPLETED'::text, 'FAILED'::text, 'ROLLED_BACK'::text])))
);


--
-- Name: cutover_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cutover_state (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid NOT NULL,
    state text DEFAULT 'PREPARING'::text NOT NULL,
    phase text DEFAULT 'verification'::text NOT NULL,
    verification_status text DEFAULT 'pending'::text NOT NULL,
    verification_report jsonb DEFAULT '{}'::jsonb NOT NULL,
    grace_period_hours integer DEFAULT 72 NOT NULL,
    grace_period_started_at timestamp with time zone,
    grace_period_completed_at timestamp with time zone,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    target_mail_server text,
    CONSTRAINT cutover_state_phase_check CHECK ((phase = ANY (ARRAY['verification'::text, 'approval'::text, 'cutover'::text, 'grace'::text, 'completion'::text, 'rollback'::text]))),
    CONSTRAINT cutover_state_state_check CHECK ((state = ANY (ARRAY['PREPARING'::text, 'READY_FOR_CUTOVER'::text, 'APPROVED'::text, 'CUTOVER_IN_PROGRESS'::text, 'GRACE_PERIOD'::text, 'COMPLETED'::text, 'FAILED'::text, 'ROLLED_BACK'::text]))),
    CONSTRAINT cutover_state_verification_status_check CHECK ((verification_status = ANY (ARRAY['pending'::text, 'pass'::text, 'fail'::text, 'warn'::text, 'skipped'::text])))
);


--
-- Name: decision; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.decision (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid,
    category text NOT NULL,
    summary text NOT NULL,
    detail jsonb DEFAULT '{}'::jsonb NOT NULL,
    proposed_default text,
    status text DEFAULT 'pending'::text NOT NULL,
    resolution jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    resolved_at timestamp with time zone,
    resolved_by text,
    CONSTRAINT decision_category_check CHECK ((category = ANY (ARRAY['new_mailbox'::text, 'deleted_mailbox'::text, 'quota'::text, 'shared_address_pattern'::text, 'offboarding'::text, 'alias_removed'::text, 'new_domain'::text, 'rules_detected'::text, 'target_drift'::text, 'other'::text]))),
    CONSTRAINT decision_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'resolved'::text, 'auto_resolved'::text, 'dismissed'::text])))
);

ALTER TABLE ONLY public.decision FORCE ROW LEVEL SECURITY;


--
-- Name: group_def; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_def (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    source_connection_id uuid NOT NULL,
    address text NOT NULL,
    members jsonb DEFAULT '[]'::jsonb NOT NULL,
    target_group_ref text,
    status text DEFAULT 'pending'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT group_def_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'created'::text, 'error'::text])))
);

ALTER TABLE ONLY public.group_def FORCE ROW LEVEL SECURITY;


--
-- Name: item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid NOT NULL,
    domain text NOT NULL,
    collection text NOT NULL,
    natural_key text NOT NULL,
    natural_key_hash text NOT NULL,
    content_hash text,
    size_bytes bigint,
    source_ref jsonb DEFAULT '{}'::jsonb NOT NULL,
    target_ref jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    attempt_count integer DEFAULT 0 NOT NULL,
    last_error text,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    last_synced_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    item_type text DEFAULT 'mail'::text NOT NULL,
    source_version text,
    moved_to_collection text,
    move_acknowledged_at timestamp with time zone,
    target_version text,
    absent_passes integer DEFAULT 0 NOT NULL,
    deletion_acknowledged_at timestamp with time zone,
    source_ref_href text,
    deletion_reported_at timestamp with time zone,
    deletion_trashed_at timestamp with time zone,
    deletion_applied_at timestamp with time zone,
    CONSTRAINT item_domain_check CHECK ((domain = ANY (ARRAY['email'::text, 'calendar'::text, 'contact'::text, 'file'::text]))),
    CONSTRAINT item_item_type_check CHECK ((item_type = ANY (ARRAY['mail'::text, 'calendar'::text, 'contact'::text, 'file'::text]))),
    CONSTRAINT item_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'copied'::text, 'updated'::text, 'adopted'::text, 'skipped'::text, 'failed'::text, 'left_behind'::text, 'deleted_source'::text, 'tombstoned'::text])))
);

ALTER TABLE ONLY public.item FORCE ROW LEVEL SECURITY;


--
-- Name: mailbox; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mailbox (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    connection_id uuid NOT NULL,
    external_id text,
    kind text DEFAULT 'user'::text NOT NULL,
    primary_address text,
    display_name text,
    quota_bytes bigint,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT mailbox_kind_check CHECK ((kind = ANY (ARRAY['user'::text, 'shared'::text, 'archive'::text, 'resource'::text]))),
    CONSTRAINT mailbox_status_check CHECK ((status = ANY (ARRAY['active'::text, 'deleted_source'::text, 'disabled'::text])))
);

ALTER TABLE ONLY public.mailbox FORCE ROW LEVEL SECURITY;


--
-- Name: mailbox_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mailbox_mapping (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    source_mailbox_id uuid NOT NULL,
    target_mailbox_id uuid,
    pattern text,
    mode text DEFAULT 'mirror'::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    name text,
    schedule text,
    CONSTRAINT mailbox_mapping_mode_check CHECK ((mode = ANY (ARRAY['mirror'::text, 'bidirectional'::text, 'one_time'::text, 'asymmetric'::text]))),
    CONSTRAINT mailbox_mapping_pattern_check CHECK ((pattern = ANY (ARRAY['shared_s'::text, 'distribution_d'::text]))),
    CONSTRAINT mailbox_mapping_status_check CHECK ((status = ANY (ARRAY['active'::text, 'paused'::text, 'cutover'::text, 'done'::text])))
);

ALTER TABLE ONLY public.mailbox_mapping FORCE ROW LEVEL SECURITY;


--
-- Name: migration_discovery; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.migration_discovery (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid NOT NULL,
    domain text NOT NULL,
    collections integer DEFAULT 0 NOT NULL,
    items integer DEFAULT 0 NOT NULL,
    bytes bigint,
    per_collection jsonb,
    last_error text,
    discovered_at timestamp with time zone DEFAULT now() NOT NULL,
    generated_id_items integer,
    target_existing integer,
    target_colliding integer,
    CONSTRAINT migration_discovery_domain_check CHECK ((domain = ANY (ARRAY['email'::text, 'calendar'::text, 'contact'::text, 'file'::text])))
);


--
-- Name: migration_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.migration_status (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid NOT NULL,
    domain text NOT NULL,
    state text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    last_error text,
    last_pass_metrics jsonb,
    CONSTRAINT migration_status_domain_check CHECK ((domain = ANY (ARRAY['email'::text, 'calendar'::text, 'contact'::text, 'file'::text]))),
    CONSTRAINT migration_status_state_check CHECK ((state = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'failed'::text, 'skipped'::text])))
);


--
-- Name: policy_preset; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.policy_preset (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    category text NOT NULL,
    action text DEFAULT 'ask'::text NOT NULL,
    params jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT policy_preset_action_check CHECK ((action = ANY (ARRAY['auto'::text, 'ask'::text])))
);

ALTER TABLE ONLY public.policy_preset FORCE ROW LEVEL SECURITY;


--
-- Name: run; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.run (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid,
    kind text NOT NULL,
    trigger text DEFAULT 'schedule'::text NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    orchestrator_ref text,
    stats jsonb DEFAULT '{}'::jsonb NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT run_kind_check CHECK ((kind = ANY (ARRAY['initial_copy'::text, 'incremental'::text, 'cutover'::text, 'verify'::text, 'discovery'::text, 'backup'::text]))),
    CONSTRAINT run_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'cancelled'::text]))),
    CONSTRAINT run_trigger_check CHECK ((trigger = ANY (ARRAY['schedule'::text, 'manual'::text, 'event'::text])))
);

ALTER TABLE ONLY public.run FORCE ROW LEVEL SECURITY;


--
-- Name: run_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.run_event (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    run_id uuid NOT NULL,
    level text DEFAULT 'info'::text NOT NULL,
    message text NOT NULL,
    detail jsonb,
    at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT run_event_level_check CHECK ((level = ANY (ARRAY['debug'::text, 'info'::text, 'warn'::text, 'error'::text])))
);

ALTER TABLE ONLY public.run_event FORCE ROW LEVEL SECURITY;


--
-- Name: scope_selection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scope_selection (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid NOT NULL,
    domain text NOT NULL,
    included boolean DEFAULT true NOT NULL,
    filters jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT scope_selection_domain_check CHECK ((domain = ANY (ARRAY['email'::text, 'calendar'::text, 'contact'::text, 'file'::text])))
);

ALTER TABLE ONLY public.scope_selection FORCE ROW LEVEL SECURITY;


--
-- Name: sync_checkpoint; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sync_checkpoint (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid NOT NULL,
    domain text NOT NULL,
    collection text NOT NULL,
    source_token jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_full_scan_at timestamp with time zone,
    last_delta_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sync_checkpoint_domain_check CHECK ((domain = ANY (ARRAY['email'::text, 'calendar'::text, 'contact'::text, 'file'::text])))
);

ALTER TABLE ONLY public.sync_checkpoint FORCE ROW LEVEL SECURITY;


--
-- Name: tenant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenant (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    settings jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT tenant_status_check CHECK ((status = ANY (ARRAY['active'::text, 'suspended'::text, 'deleting'::text])))
);

ALTER TABLE ONLY public.tenant FORCE ROW LEVEL SECURITY;


--
-- Name: verification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tenant_id uuid NOT NULL,
    mapping_id uuid NOT NULL,
    run_id uuid,
    domain text NOT NULL,
    collection text,
    source_count bigint,
    target_count bigint,
    source_bytes bigint,
    target_bytes bigint,
    checksum_sampled integer DEFAULT 0,
    checksum_mismatches integer DEFAULT 0,
    status text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT verification_domain_check CHECK ((domain = ANY (ARRAY['email'::text, 'calendar'::text, 'contact'::text, 'file'::text]))),
    CONSTRAINT verification_status_check CHECK ((status = ANY (ARRAY['pass'::text, 'warn'::text, 'fail'::text])))
);

ALTER TABLE ONLY public.verification FORCE ROW LEVEL SECURITY;


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: backup_target backup_target_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_target
    ADD CONSTRAINT backup_target_pkey PRIMARY KEY (id);


--
-- Name: collection_mapping collection_mapping_mapping_id_domain_source_collection_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_mapping
    ADD CONSTRAINT collection_mapping_mapping_id_domain_source_collection_key UNIQUE (mapping_id, domain, source_collection);


--
-- Name: collection_mapping collection_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_mapping
    ADD CONSTRAINT collection_mapping_pkey PRIMARY KEY (id);


--
-- Name: connection connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.connection
    ADD CONSTRAINT connection_pkey PRIMARY KEY (id);


--
-- Name: cursor cursor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cursor
    ADD CONSTRAINT cursor_pkey PRIMARY KEY (id);


--
-- Name: cursor cursor_tenant_id_mapping_id_folder_path_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cursor
    ADD CONSTRAINT cursor_tenant_id_mapping_id_folder_path_key UNIQUE (tenant_id, mapping_id, folder_path);


--
-- Name: cutover_event cutover_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cutover_event
    ADD CONSTRAINT cutover_event_pkey PRIMARY KEY (id);


--
-- Name: cutover cutover_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cutover
    ADD CONSTRAINT cutover_pkey PRIMARY KEY (id);


--
-- Name: cutover_state cutover_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cutover_state
    ADD CONSTRAINT cutover_state_pkey PRIMARY KEY (id);


--
-- Name: cutover_state cutover_state_tenant_id_mapping_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cutover_state
    ADD CONSTRAINT cutover_state_tenant_id_mapping_id_key UNIQUE (tenant_id, mapping_id);


--
-- Name: decision decision_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision
    ADD CONSTRAINT decision_pkey PRIMARY KEY (id);


--
-- Name: group_def group_def_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_def
    ADD CONSTRAINT group_def_pkey PRIMARY KEY (id);


--
-- Name: item item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_pkey PRIMARY KEY (id);


--
-- Name: item item_tenant_mapping_type_natural_key_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_tenant_mapping_type_natural_key_unique UNIQUE (tenant_id, mapping_id, item_type, natural_key_hash);


--
-- Name: mailbox mailbox_connection_id_external_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mailbox
    ADD CONSTRAINT mailbox_connection_id_external_id_key UNIQUE (connection_id, external_id);


--
-- Name: mailbox_mapping mailbox_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mailbox_mapping
    ADD CONSTRAINT mailbox_mapping_pkey PRIMARY KEY (id);


--
-- Name: mailbox_mapping mailbox_mapping_source_mailbox_id_target_mailbox_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mailbox_mapping
    ADD CONSTRAINT mailbox_mapping_source_mailbox_id_target_mailbox_id_key UNIQUE (source_mailbox_id, target_mailbox_id);


--
-- Name: mailbox mailbox_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mailbox
    ADD CONSTRAINT mailbox_pkey PRIMARY KEY (id);


--
-- Name: migration_discovery migration_discovery_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_discovery
    ADD CONSTRAINT migration_discovery_pkey PRIMARY KEY (id);


--
-- Name: migration_discovery migration_discovery_tenant_id_mapping_id_domain_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_discovery
    ADD CONSTRAINT migration_discovery_tenant_id_mapping_id_domain_key UNIQUE (tenant_id, mapping_id, domain);


--
-- Name: migration_status migration_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_status
    ADD CONSTRAINT migration_status_pkey PRIMARY KEY (id);


--
-- Name: migration_status migration_status_tenant_id_mapping_id_domain_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_status
    ADD CONSTRAINT migration_status_tenant_id_mapping_id_domain_key UNIQUE (tenant_id, mapping_id, domain);


--
-- Name: policy_preset policy_preset_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_preset
    ADD CONSTRAINT policy_preset_pkey PRIMARY KEY (id);


--
-- Name: policy_preset policy_preset_tenant_id_category_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_preset
    ADD CONSTRAINT policy_preset_tenant_id_category_key UNIQUE (tenant_id, category);


--
-- Name: run_event run_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_event
    ADD CONSTRAINT run_event_pkey PRIMARY KEY (id);


--
-- Name: run run_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run
    ADD CONSTRAINT run_pkey PRIMARY KEY (id);


--
-- Name: scope_selection scope_selection_mapping_id_domain_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scope_selection
    ADD CONSTRAINT scope_selection_mapping_id_domain_key UNIQUE (mapping_id, domain);


--
-- Name: scope_selection scope_selection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scope_selection
    ADD CONSTRAINT scope_selection_pkey PRIMARY KEY (id);


--
-- Name: sync_checkpoint sync_checkpoint_mapping_id_domain_collection_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_checkpoint
    ADD CONSTRAINT sync_checkpoint_mapping_id_domain_collection_key UNIQUE (mapping_id, domain, collection);


--
-- Name: sync_checkpoint sync_checkpoint_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_checkpoint
    ADD CONSTRAINT sync_checkpoint_pkey PRIMARY KEY (id);


--
-- Name: tenant tenant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant
    ADD CONSTRAINT tenant_pkey PRIMARY KEY (id);


--
-- Name: verification verification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification
    ADD CONSTRAINT verification_pkey PRIMARY KEY (id);


--
-- Name: ix_audit_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_audit_tenant ON public.audit_log USING btree (tenant_id, at DESC);


--
-- Name: ix_connection_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_connection_tenant ON public.connection USING btree (tenant_id);


--
-- Name: ix_cursor_tenant_mapping; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_cursor_tenant_mapping ON public.cursor USING btree (tenant_id, mapping_id);


--
-- Name: ix_cutover_event_mapping; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_cutover_event_mapping ON public.cutover_event USING btree (mapping_id, "timestamp");


--
-- Name: ix_cutover_event_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_cutover_event_tenant ON public.cutover_event USING btree (tenant_id, "timestamp");


--
-- Name: ix_cutover_state_mapping; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_cutover_state_mapping ON public.cutover_state USING btree (mapping_id);


--
-- Name: ix_cutover_state_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_cutover_state_tenant ON public.cutover_state USING btree (tenant_id);


--
-- Name: ix_decision_pending; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_decision_pending ON public.decision USING btree (tenant_id, status) WHERE (status = 'pending'::text);


--
-- Name: ix_group_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_group_tenant ON public.group_def USING btree (tenant_id);


--
-- Name: ix_item_absent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_item_absent ON public.item USING btree (tenant_id, mapping_id, domain) WHERE (absent_passes > 0);


--
-- Name: ix_item_collection; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_item_collection ON public.item USING btree (tenant_id, mapping_id, domain, collection);


--
-- Name: ix_item_content; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_item_content ON public.item USING btree (content_hash);


--
-- Name: ix_item_failed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_item_failed ON public.item USING btree (tenant_id, mapping_id, domain) WHERE (status = 'failed'::text);


--
-- Name: ix_item_moved; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_item_moved ON public.item USING btree (tenant_id, mapping_id, domain) WHERE (moved_to_collection IS NOT NULL);


--
-- Name: ix_item_source_ref; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_item_source_ref ON public.item USING btree (tenant_id, mapping_id, domain, source_ref_href) WHERE (source_ref_href IS NOT NULL);


--
-- Name: ix_item_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_item_status ON public.item USING btree (tenant_id, mapping_id, status);


--
-- Name: ix_item_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_item_type ON public.item USING btree (tenant_id, mapping_id, item_type);


--
-- Name: ix_mailbox_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_mailbox_tenant ON public.mailbox USING btree (tenant_id);


--
-- Name: ix_mapping_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_mapping_tenant ON public.mailbox_mapping USING btree (tenant_id);


--
-- Name: ix_migration_discovery_tenant_mapping; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_migration_discovery_tenant_mapping ON public.migration_discovery USING btree (tenant_id, mapping_id);


--
-- Name: ix_migration_status_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_migration_status_state ON public.migration_status USING btree (state);


--
-- Name: ix_migration_status_tenant_mapping; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_migration_status_tenant_mapping ON public.migration_status USING btree (tenant_id, mapping_id);


--
-- Name: ix_run_event_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_run_event_run ON public.run_event USING btree (run_id, at);


--
-- Name: ix_run_mapping; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_run_mapping ON public.run USING btree (mapping_id, created_at DESC);


--
-- Name: ix_run_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_run_tenant ON public.run USING btree (tenant_id, created_at DESC);


--
-- Name: ix_verif_mapping; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_verif_mapping ON public.verification USING btree (mapping_id, created_at DESC);


--
-- Name: audit_log audit_log_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: backup_target backup_target_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_target
    ADD CONSTRAINT backup_target_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: backup_target backup_target_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backup_target
    ADD CONSTRAINT backup_target_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: collection_mapping collection_mapping_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_mapping
    ADD CONSTRAINT collection_mapping_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: collection_mapping collection_mapping_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.collection_mapping
    ADD CONSTRAINT collection_mapping_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: connection connection_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.connection
    ADD CONSTRAINT connection_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: cursor cursor_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cursor
    ADD CONSTRAINT cursor_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: cursor cursor_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cursor
    ADD CONSTRAINT cursor_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: cutover_event cutover_event_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cutover_event
    ADD CONSTRAINT cutover_event_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: cutover_event cutover_event_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cutover_event
    ADD CONSTRAINT cutover_event_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: cutover cutover_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cutover
    ADD CONSTRAINT cutover_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: cutover_state cutover_state_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cutover_state
    ADD CONSTRAINT cutover_state_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: cutover_state cutover_state_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cutover_state
    ADD CONSTRAINT cutover_state_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: cutover cutover_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cutover
    ADD CONSTRAINT cutover_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: decision decision_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision
    ADD CONSTRAINT decision_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: decision decision_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision
    ADD CONSTRAINT decision_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: group_def group_def_source_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_def
    ADD CONSTRAINT group_def_source_connection_id_fkey FOREIGN KEY (source_connection_id) REFERENCES public.connection(id) ON DELETE CASCADE;


--
-- Name: group_def group_def_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_def
    ADD CONSTRAINT group_def_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: item item_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: item item_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: mailbox mailbox_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mailbox
    ADD CONSTRAINT mailbox_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES public.connection(id) ON DELETE CASCADE;


--
-- Name: mailbox_mapping mailbox_mapping_source_mailbox_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mailbox_mapping
    ADD CONSTRAINT mailbox_mapping_source_mailbox_id_fkey FOREIGN KEY (source_mailbox_id) REFERENCES public.mailbox(id) ON DELETE CASCADE;


--
-- Name: mailbox_mapping mailbox_mapping_target_mailbox_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mailbox_mapping
    ADD CONSTRAINT mailbox_mapping_target_mailbox_id_fkey FOREIGN KEY (target_mailbox_id) REFERENCES public.mailbox(id) ON DELETE SET NULL;


--
-- Name: mailbox_mapping mailbox_mapping_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mailbox_mapping
    ADD CONSTRAINT mailbox_mapping_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: mailbox mailbox_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mailbox
    ADD CONSTRAINT mailbox_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: migration_discovery migration_discovery_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_discovery
    ADD CONSTRAINT migration_discovery_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: migration_discovery migration_discovery_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_discovery
    ADD CONSTRAINT migration_discovery_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: migration_status migration_status_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_status
    ADD CONSTRAINT migration_status_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: migration_status migration_status_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.migration_status
    ADD CONSTRAINT migration_status_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: policy_preset policy_preset_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.policy_preset
    ADD CONSTRAINT policy_preset_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: run_event run_event_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_event
    ADD CONSTRAINT run_event_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.run(id) ON DELETE CASCADE;


--
-- Name: run_event run_event_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_event
    ADD CONSTRAINT run_event_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: run run_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run
    ADD CONSTRAINT run_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE SET NULL;


--
-- Name: run run_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run
    ADD CONSTRAINT run_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: scope_selection scope_selection_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scope_selection
    ADD CONSTRAINT scope_selection_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: scope_selection scope_selection_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scope_selection
    ADD CONSTRAINT scope_selection_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: sync_checkpoint sync_checkpoint_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_checkpoint
    ADD CONSTRAINT sync_checkpoint_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: sync_checkpoint sync_checkpoint_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sync_checkpoint
    ADD CONSTRAINT sync_checkpoint_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: verification verification_mapping_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification
    ADD CONSTRAINT verification_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES public.mailbox_mapping(id) ON DELETE CASCADE;


--
-- Name: verification verification_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification
    ADD CONSTRAINT verification_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.run(id) ON DELETE SET NULL;


--
-- Name: verification verification_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification
    ADD CONSTRAINT verification_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant(id) ON DELETE CASCADE;


--
-- Name: audit_log; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

--
-- Name: backup_target; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.backup_target ENABLE ROW LEVEL SECURITY;

--
-- Name: collection_mapping; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.collection_mapping ENABLE ROW LEVEL SECURITY;

--
-- Name: connection; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.connection ENABLE ROW LEVEL SECURITY;

--
-- Name: cursor; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cursor ENABLE ROW LEVEL SECURITY;

--
-- Name: cutover; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.cutover ENABLE ROW LEVEL SECURITY;

--
-- Name: decision; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.decision ENABLE ROW LEVEL SECURITY;

--
-- Name: group_def; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.group_def ENABLE ROW LEVEL SECURITY;

--
-- Name: item; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.item ENABLE ROW LEVEL SECURITY;

--
-- Name: mailbox; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.mailbox ENABLE ROW LEVEL SECURITY;

--
-- Name: mailbox_mapping; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.mailbox_mapping ENABLE ROW LEVEL SECURITY;

--
-- Name: migration_discovery; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.migration_discovery ENABLE ROW LEVEL SECURITY;

--
-- Name: migration_status; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.migration_status ENABLE ROW LEVEL SECURITY;

--
-- Name: policy_preset; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.policy_preset ENABLE ROW LEVEL SECURITY;

--
-- Name: run; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.run ENABLE ROW LEVEL SECURITY;

--
-- Name: run_event; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.run_event ENABLE ROW LEVEL SECURITY;

--
-- Name: scope_selection; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.scope_selection ENABLE ROW LEVEL SECURITY;

--
-- Name: sync_checkpoint; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.sync_checkpoint ENABLE ROW LEVEL SECURITY;

--
-- Name: tenant; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.tenant ENABLE ROW LEVEL SECURITY;

--
-- Name: audit_log tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.audit_log FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: backup_target tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.backup_target FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: collection_mapping tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.collection_mapping FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: connection tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.connection FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: cursor tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.cursor FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: cutover tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.cutover FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: decision tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.decision FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: group_def tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.group_def FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: item tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.item FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: mailbox tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.mailbox FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: mailbox_mapping tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.mailbox_mapping FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: migration_discovery tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.migration_discovery FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: migration_status tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.migration_status FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: policy_preset tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.policy_preset FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: run tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.run FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: run_event tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.run_event FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: scope_selection tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.scope_selection FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: sync_checkpoint tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.sync_checkpoint FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: tenant tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.tenant FOR DELETE USING ((id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: verification tenant_isolation_delete; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_delete ON public.verification FOR DELETE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: audit_log tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.audit_log FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: backup_target tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.backup_target FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: collection_mapping tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.collection_mapping FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: connection tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.connection FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: cursor tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.cursor FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: cutover tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.cutover FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: decision tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.decision FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: group_def tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.group_def FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: item tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.item FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: mailbox tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.mailbox FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: mailbox_mapping tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.mailbox_mapping FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: migration_discovery tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.migration_discovery FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: migration_status tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.migration_status FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: policy_preset tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.policy_preset FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: run tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.run FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: run_event tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.run_event FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: scope_selection tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.scope_selection FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: sync_checkpoint tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.sync_checkpoint FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: tenant tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.tenant FOR INSERT WITH CHECK ((id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: verification tenant_isolation_insert; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_insert ON public.verification FOR INSERT WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: audit_log tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.audit_log FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: backup_target tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.backup_target FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: collection_mapping tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.collection_mapping FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: connection tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.connection FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: cursor tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.cursor FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: cutover tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.cutover FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: decision tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.decision FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: group_def tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.group_def FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: item tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.item FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: mailbox tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.mailbox FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: mailbox_mapping tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.mailbox_mapping FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: migration_discovery tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.migration_discovery FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: migration_status tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.migration_status FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: policy_preset tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.policy_preset FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: run tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.run FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: run_event tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.run_event FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: scope_selection tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.scope_selection FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: sync_checkpoint tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.sync_checkpoint FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: tenant tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.tenant FOR SELECT USING ((id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: verification tenant_isolation_select; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_select ON public.verification FOR SELECT USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: audit_log tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.audit_log FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: backup_target tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.backup_target FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: collection_mapping tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.collection_mapping FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: connection tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.connection FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: cursor tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.cursor FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: cutover tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.cutover FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: decision tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.decision FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: group_def tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.group_def FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: item tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.item FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: mailbox tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.mailbox FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: mailbox_mapping tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.mailbox_mapping FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: migration_discovery tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.migration_discovery FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: migration_status tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.migration_status FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: policy_preset tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.policy_preset FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: run tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.run FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: run_event tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.run_event FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: scope_selection tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.scope_selection FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: sync_checkpoint tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.sync_checkpoint FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: tenant tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.tenant FOR UPDATE USING ((id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: verification tenant_isolation_update; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY tenant_isolation_update ON public.verification FOR UPDATE USING ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid)) WITH CHECK ((tenant_id = (current_setting('app.current_tenant'::text, true))::uuid));


--
-- Name: verification; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.verification ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

GRANT USAGE ON SCHEMA public TO app_user;


--
-- Name: TABLE audit_log; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.audit_log TO app_user;


--
-- Name: TABLE backup_target; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.backup_target TO app_user;


--
-- Name: TABLE collection_mapping; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.collection_mapping TO app_user;


--
-- Name: TABLE connection; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.connection TO app_user;


--
-- Name: TABLE cursor; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.cursor TO app_user;


--
-- Name: TABLE cutover; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.cutover TO app_user;


--
-- Name: TABLE cutover_event; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.cutover_event TO app_user;


--
-- Name: TABLE cutover_state; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.cutover_state TO app_user;


--
-- Name: TABLE decision; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.decision TO app_user;


--
-- Name: TABLE group_def; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.group_def TO app_user;


--
-- Name: TABLE item; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.item TO app_user;


--
-- Name: TABLE mailbox; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.mailbox TO app_user;


--
-- Name: TABLE mailbox_mapping; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.mailbox_mapping TO app_user;


--
-- Name: TABLE migration_discovery; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.migration_discovery TO app_user;


--
-- Name: TABLE migration_status; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.migration_status TO app_user;


--
-- Name: TABLE policy_preset; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.policy_preset TO app_user;


--
-- Name: TABLE run; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.run TO app_user;


--
-- Name: TABLE run_event; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.run_event TO app_user;


--
-- Name: TABLE scope_selection; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.scope_selection TO app_user;


--
-- Name: TABLE sync_checkpoint; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.sync_checkpoint TO app_user;


--
-- Name: TABLE tenant; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.tenant TO app_user;


--
-- Name: TABLE verification; Type: ACL; Schema: public; Owner: -
--

GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE public.verification TO app_user;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,USAGE ON SEQUENCES TO app_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: -
--

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO app_user;


--
-- PostgreSQL database dump complete
--


