-- Copyright 2026 The Open Migration Stack authors (Apache-2.0)
--
-- The TARGET's own version marker (an ETag) for the copy as we last wrote it.
--
-- Migration 0020 added `source_version` so a pass could tell that the source had
-- moved on. This is the mirror image, and it closes the one path in the product
-- where a person's data can actually be destroyed.
--
-- Shadow migration invites the owner to start using the new system before
-- cutover. Suppose they do: they open an event we copied and correct the time.
-- Later the same event changes on the source. `classifyKnownItem` sees a row we
-- wrote ourselves (status 'copied'), decides the bytes are ours to replace —
-- which was true when we wrote them — and the pass overwrites their correction
-- without reading it, counting `updated: 1`. Nothing is logged, nothing fails,
-- and the edit is gone.
--
-- Hard rule 2 says never auto-overwrite on the target. The rule was being
-- enforced against a stale idea of ownership: 'copied' meant "we wrote this",
-- not "this is still what we wrote".
--
-- So: record what the server said the object was after our write, and check it
-- still says the same thing before replacing it. An ETag rather than a hash of
-- the bytes, deliberately — CalDAV and CardDAV servers may normalise what they
-- store, so a re-read can differ from what we sent for reasons that have
-- nothing to do with anyone editing it. Comparing content would then declare
-- every rewrite a conflict and quietly freeze the whole corpus. The ETag is
-- minted by the server AFTER any normalisation, so it changes when, and only
-- when, the object does.
--
-- NULL means "not known", and never blocks a write:
--
--   * every row written before this migration;
--   * any server that does not return an ETag on PUT.
--
-- Those keep exactly the behaviour they have today. Failing closed instead
-- would refuse to propagate a single source change until every row had been
-- rewritten once — turning a protection into an outage.

ALTER TABLE item ADD COLUMN IF NOT EXISTS target_version text;
