-- Copyright 2026 The Open Migration Stack authors (Apache-2.0)
--
-- When we found a copy of an item in the owner's BIN on the source.
--
-- The third kind of deletion evidence, after `absent_passes` (0024, inferred from
-- repeated absence) and `deletion_reported_at` (0026, the server's own RFC 6578
-- removal report). It is the only one MAIL has: IMAP offers no removal report in
-- the shape 0026 needs, and a mailbox cannot be enumerated cheaply enough for
-- absence-counting to be affordable on every pass. Until now a message the owner
-- deleted in the old system produced nothing at all — the target kept its copy in
-- silence, and no surface anywhere said so.
--
-- WHAT MAKES IT EVIDENCE. An item sitting in a collection whose RFC 6154 role is
-- `\Trash` is the source system's own record that the person deleted it. That is
-- a POSITIVE observation — we are looking at the item, not failing to find it —
-- so like a removal report it needs no corroboration and no second pass. It also
-- only became available once migration 0022's work made trash and junk
-- out-of-scope as CONTENT: what the migration no longer copies, it can read as a
-- signal.
--
-- A DIFFERENT CLAIM FROM 0026, not a weaker one. A reported deletion says the
-- object is gone; this says the owner binned it. The object still exists, the bin
-- may be emptied, and the item may be dragged back out. So it gets its own
-- column: ranked below `deletion_reported_at` when both apply, and never
-- overwriting it, because each date records when a different thing was learned.
--
-- JUNK IS DELIBERATELY NOT THIS. A message in Junk was very likely classified
-- there by a filter rather than deleted by a person, and the whole value of this
-- signal is that it is unambiguous owner intent. Junk stays out of scope as
-- content and says nothing about lifecycle.
--
-- Cleared by `clearAbsent` along with the count and the report: a message dragged
-- out of Deleted Items back into the inbox is demonstrably not deleted, and a
-- stale claim that the owner threw something away is exactly the kind that must
-- not survive.

ALTER TABLE item ADD COLUMN IF NOT EXISTS deletion_trashed_at timestamptz;

-- No index, for the same reason as 0026: every read of this column happens inside
-- a query already filtered by (tenant_id, mapping_id[, domain]), and the
-- deletions queue scans those rows anyway to compare `absent_passes`. A fifth
-- partial index on this table would cost every insert and buy nothing measurable.
